version: "3.8"

services:

  mongodb:
    image: mongo:7
    container_name: easyshop-mongodb

    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

  frontend:
    build: .

    container_name: easyshop-frontend

    restart: always

    depends_on:
      - mongodb

    ports:
      - "3000:3000"

    environment:
      MONGODB_URI: mongodb://mongodb:27017/easyshop      
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      NEXTAUTH_SECRET: HmaFjYZ2jbUK7Ef+wZrBiJei4ZNGBAJ5IdiOGAyQegw=
      JWT_SECRET: e5e425764a34a2117ec2028bd53d6f1388e7b90aeae9fa7735f2469ea3a6cc8c

volumes:
  mongodb_data: